### ISSUE TITLE
Can't annotate the result of `mock.patch.object`

### ISSUE THREAD

**Issue by mikolajz** [python/typeshed#10838]
We have the following code (simplified):
```
class SomeTestRunner:
    def __init__(self):
        ...
        self._patch_wait_for_something: Optional[mock._patch[mock.MagicMock]] = None  # <--

    def start():
        ...
        self._patch_wait_for_something = mock.patch.object(target=self._something, attribute="_wait_something")
        mock_wait_for_somethihng = self._patch_wait_for_something.start()
        ...

    def stop():
        ...
       self._patch_wait_for_something.stop()
        ...
```

This used to work in types-mock==0.1.2, but fails in types-mock==5.1.0.2 because of the line marked with `<--`: `some/path.py:302: error: Name "mock._patch" is not defined  [name-defined]`. It seems this is because `_patch` is not in `__all__` and probably the older types module was considered incomplete and allowed for such things.

Is there a way to annotate it in current versions of `mock` other than `Any`?

**Comment by srittau** [comment]
We usually try to mimic runtime as best as possible. In this case, `_patch` is not re-exported from `mock`:

```python
>>> import mock
>>> mock._patch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'mock' has no attribute '_patch'. Did you mean: 'patch'?
```

Using `mock.mock._patch` instead should work, though:

```python
>>> mock.mock._patch
<class 'mock.mock._patch'>
```

**Comment by mikolajz** [comment]
This works. We haven't thought about it. Thanks!
