### PR TITLE
Change return annotation of Popen.poll to Optional[int] (#3984)

### LINKED ISSUE #3984: `Popen.poll` return annotation should be `Optional[int]`
https://github.com/python/typeshed/blob/2ead8123a6c2b485b163ca48a962c9f3a7d52708/stdlib/3/subprocess.pyi#L1158

whereas the [subprocess docs](https://docs.python.org/3/library/subprocess.html#subprocess.Popen.poll) say:

> Check if child process has terminated. Set and return returncode attribute. Otherwise, returns None.

Example of where this raises a false positive:

```python
# test.py
import subprocess
import sys
import time

proc = subprocess.Popen([sys.executable, "-c", "import time; time.sleep(5)"])
while True:
    exitcode = proc.poll()
    print("exitcode", exitcode)
    if exitcode is not None:
        break
    time.sleep(1)  # this is line 10
```

```
$ mypy --warn-unreachable test.py
test.py:10: error: Statement is unreachable
```

whereas the program's output is:
```
$ python test.py
exitcode None
exitcode None
exitcode None
exitcode None
exitcode None
exitcode None
exitcode 0
```

I'd be happy to submit a PR!

### PR DESCRIPTION
**Pull request by selimb**
Fixes #3984

### CODE REVIEW

**Comment by selimb** [comment]
Looks like the build is failing since #3834?
