### PR TITLE
Fix _DispatchProtocol in xmlrpc.server

### LINKED ISSUE #4163: Error checking SimpleXMLRPCServer.register_function arguments
* Are you reporting a bug, or opening a feature request?
Bug Report

* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.

```
from xmlrpc.server import SimpleXMLRPCRequestHandler, SimpleXMLRPCServer
  
def f():
        pass


server = SimpleXMLRPCServer(
        ('127.0.0.1', 5000),
        requestHandler=SimpleXMLRPCRequestHandler,
        allow_none=True,
)
server.register_function(function=f)
```
* What is the actual behavior/output?

test.py:12: error: Argument "function" to "register_function" of "SimpleXMLRPCDispatcher" has incompatible type "Callable[[], Any]"; expected "Optional[_DispatchProtocol]"

* What is the behavior/output you expect?

No errors.

* What are the versions of mypy and Python you are using?

I've tried with Python versiond 3.5.9 and 3.7.7.

This error only started to appear after upgrading mypy to 0.780. Reverting to mypy 0.770 resolved the issue. 

* What are the mypy flags you are using? (For example --strict-optional)

`--ignore-missing-imports`

### PR DESCRIPTION
**Pull request by CraftSpider**
Closes #4163
Mypy treats protocols strictly, so allow common cases explicitly. It would probably also be good to allows a subset of Marshallable as accepted argument inputs, but I'm not sure how to convey the desired 'Any subset of this union' to mypy. Feel free to supersede this, if anyone knows how to better convey the intended design to type checkers.

### CODE REVIEW

File: stdlib/3/xmlrpc/server.pyi [hunk 1]
```diff
@@ -7,9 +7,19 @@ from xmlrpc.client import Fault
...
-class _DispatchProtocol(Protocol):
+_Marshallable = Union[None, bool, int, float, str, bytes, tuple, list, dict, datetime]  # TODO: Recursive type on tuple, list, dict
+
+# The dispatch accepts anywhere from 0 to N arguments, no easy way to allow this in mypy
+class _DispatchArity0(Protocol):
+    def __call__(self) -> _Marshallable: ...
+class _DispatchArity1(Protocol):
+    def __call__(self, __arg1: _Marshallable) -> _Marshallable: ...
+class _DispatchArity2(Protocol):
+    def __call__(self, __arg1: _Marshallable, __arg2: _Marshallable) -> _Marshallable: ...
```
Comment (JelleZijlstra) [inline stdlib/3/xmlrpc/server.pyi:18]: I don't really know xmlrpc, but how likely is it that somebody would patch a fixed-arity dispatcher with more than two arguments? Maybe to be safe we should add arity 3 and 4 versions.

Comment (CraftSpider) [reply stdlib/3/xmlrpc/server.pyi:18]: I'm honestly not sure the likelihood. I'll add the 3/4 arity versions, as it doesn't hurt to do so
