### ISSUE TITLE
fcntl.flock no longer typechecks with io.FileIO argument

### ISSUE THREAD

**Issue by EvanKrall** [python/typeshed#1548]
Seems like an edge case broken by the change in https://github.com/python/typeshed/pull/1505:

This code works in reality, but mypy does not like it:

```python
import io
import fcntl


with io.FileIO('hello.txt', mode='a+', closefd=True) as f:
    fcntl.flock(f, fcntl.LOCK_EX)
    print("hey it works")
    fcntl.flock(f, fcntl.LOCK_UN)
```

```
$ python ./blurp.py
hey it works
$ mypy ./blurp.py
blurp.py:6: error: Argument 1 to "flock" has incompatible type "IOBase"; expected "Union[int, IO[Any]]"
blurp.py:8: error: Argument 1 to "flock" has incompatible type "IOBase"; expected "Union[int, IO[Any]]"
```

**Comment by OddBloke** [comment]
#1505 was a change to the Python 2 type definitions, so I don't think that will be the root of this. A bisect suggests that the Python 3 problem was actually introduced way back in https://github.com/python/typeshed/commit/9fdac6e0df7a47a147cf44796bb469a2882203a7 when the io module was refactored.

I _think_ adding IOBase to the acceptable types would be the correct fix here.

(In fact, with my fix for #1553 applied, your example seems to work fine with `mypy --py2`.)

**Comment by OddBloke** [comment]
(As a sidenote, this seems like it would be a great candidate for using a protocol once those finally filter out far enough for use in typeshed.)
