### ISSUE TITLE
SynchronizedArray should support slicing

### ISSUE THREAD

**Issue by prauscher** [python/typeshed#11572]
Hello everyone,

while checking multiprocessing-code, I found a bug in the following example:
```python
from multiprocessing import Value, Array
from ctypes import c_wchar_p, c_int

a = Array(c_int, 10)
print(a[0:4])
a[:] = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
```

This is roughly equivalent to the example-code in https://docs.python.org/3/library/multiprocessing.html#sharing-state-between-processes, and as expected, the code works fine on my python 3.11 (and 3.12).

If i run mypy (version 1.9.0, but from my understanding this should be a bug here in typeshed), i get
```
test.py:5: error: Invalid index type "slice" for "SynchronizedArray[c_int]"; expected type "int"  [index]
test.py:6: error: Invalid index type "slice" for "SynchronizedArray[c_int]"; expected type "int"  [index]
test.py:6: error: Incompatible types in assignment (expression has type "list[int]", target has type "c_int")  [assignment]
Found 3 errors in 1 file (checked 1 source file)
```

It seems as slicing the Array as done in the documentation is not supported in typeshed, as `SynchronizedArray` expects only int-indices. Also the return value of such an index seems to be off, as this one should be `list[int]`, and setting the value should be possible as documented.

Confusing to me, https://github.com/python/typeshed/blob/main/stdlib/multiprocessing/sharedctypes.pyi#L96 looks correct for this case, but mypy seems to pick `__getitem__` instead of `__getslice__`?

**Comment by AlexWaygood** [comment]
> mypy seems to pick `__getitem__` instead of `__getslice__`?

`__getslice__` doesn't do anything in Python 3; the existence of that method at runtime is likely something leftover from Python 2 that nobody has ever had any reason to delete. To fix this issue, `__getitem__` would need to be overloaded like we do for other sequences in typeshed, for example:

https://github.com/python/typeshed/blob/3802899a01269df575ea32a21534c5400fb9218a/stdlib/builtins.pyi#L1000-L1003

**Comment by prauscher** [comment]
Ahh, thanks. I just tested this in a venv, and replacing both `__getitem__` and `__setitem__` lines with
```python
    @overload
    def __getitem__(self, s: slice) -> list[_CT]: ...
    @overload
    def __setitem__(self, s: slice, value: Iterable[_CT]) -> None: ...
    @overload
    def __getitem__(self, i: int) -> _CT: ...
    @overload
    def __setitem__(self, i: int, value: _CT) -> None: ...
```

Seems to work, as long as the slice-lines are above the regular items. If this looks good to you I'm confident I can provide a PR

**Comment by AlexWaygood** [comment]
looks fine to me, though I'd put the two `__getitem__` overloads next to each other, and the two `__setitem__` overloads next to each other

**Comment by prauscher** [comment]
To be clear: this only fixes the bug I specified here. The new result is
```
test.py:6: error: List item 0 has incompatible type "int"; expected "c_int"  [list-item]
test.py:6: error: List item 1 has incompatible type "int"; expected "c_int"  [list-item]
test.py:6: error: List item 2 has incompatible type "int"; expected "c_int"  [list-item]
test.py:6: error: List item 3 has incompatible type "int"; expected "c_int"  [list-item]
test.py:6: error: List item 4 has incompatible type "int"; expected "c_int"  [list-item]
test.py:6: error: List item 5 has incompatible type "int"; expected "c_int"  [list-item]
test.py:6: error: List item 6 has incompatible type "int"; expected "c_int"  [list-item]
test.py:6: error: List item 7 has incompatible type "int"; expected "c_int"  [list-item]
test.py:6: error: List item 8 has incompatible type "int"; expected "c_int"  [list-item]
test.py:6: error: List item 9 has incompatible type "int"; expected "c_int"  [list-item]
```

But that seems a different issue to me
