### ISSUE TITLE
 "AbstractServer" has no attribute "sockets"

### ISSUE THREAD

**Issue by brianmay** [python/typeshed#2334]
The last line here:

```
f = self._loop.create_server(self._handler, '0.0.0.0', 8080)
self._srv = self._loop.run_until_complete(f)
logger.info('serving on %s', self._srv.sockets[0].getsockname())
```

Gives the following error:

```
robotica/plugins/inputs/http.py:88: error: "AbstractServer" has no attribute "sockets"
```

However I believe this code matches the example:

http://asyncio.readthedocs.io/en/latest/tcp_echo.html

This broke when upgrading mypy from 0.610 to 0.620.
