### PR TITLE
Add multiprocessing.pool to Python 2 stub

### LINKED ISSUE #1925: multiprocessing.pool module missing from Python 2 stubs
`multiprocessing.pool.ThreadPool` is useful (see http://lucasb.eyer.be/snips/python-thread-pool.html).

```python
import time
import multiprocessing.pool


def func(x):
    # type: (int) -> int
    time.sleep(x)
    return x


def main():
    # type: () -> None
    pool = multiprocessing.pool.ThreadPool(2)
    ite = pool.imap(func, range(10), chunksize=1)

    try:
        while True:
            x = ite.next(timeout=3)
            print(x)
    except multiprocessing.TimeoutError:
        print('timeout')
    

if __name__ == '__main__':
    main()
```

The code works on Python 2.7 as follows. (The code looks similar to #1923, but here we use `multiprocessing.pool.ThreadPool`, instead of `multiprocessing.Pool`)

```
$ python --version
Python 2.7.14
$ python bar.py
0
1
2
3
4
timeout
```

However, `mypy` fails as follows (even if we add `--ignore-missing-import`).

```
$ mypy --version
mypy 0.570-dev-c594761aa1dbe76a3a0bc199b03fbf684ce588d8
$ mypy --python-version 2.7 bar.py
bar.py:2: error: No library stub file for standard library module 'multiprocessing.pool'
bar.py:2: note: (Stub files are from https://github.com/python/typeshed)
bar.py:13: error: Module has no attribute "pool"
$ mypy --ignore-missing-import --python-version 2.7 bar.py
bar.py:13: error: Module has no attribute "pool"
```

### PR DESCRIPTION
**Pull request by iwiwi**
Fixes #1925. The new stub file for Python 2 is based on that for Python 3, including changes proposed in #1926.

Links for reviewers:
* https://github.com/python/cpython/blob/2.7/Lib/multiprocessing/pool.py
* https://docs.python.org/2.7/library/multiprocessing.html#module-multiprocessing.pool

Difference from Python 3 stub (at #1926):

```
$ diff stdlib/2/multiprocessing/pool.pyi stdlib/3/multiprocessing/pool.pyi
1c1,3
< # Stubs for multiprocessing.pool (Python 2)
---
> # Stubs for multiprocessing.pool
>
> # NOTE: These are incomplete!
23c25,26
<                  maxtasksperchild: Optional[int] = ...) -> None: ...
---
>                  maxtasksperchild: Optional[int] = ...,
>                  context: Optional[Any] = ...) -> None: ...
32c35,36
<                 callback: Optional[Callable[..., None]] = ...) -> AsyncResult: ...
---
>                 callback: Optional[Callable[..., None]] = ...,
>                 error_callback: Optional[Callable[[BaseException], None]] = ...) -> AsyncResult: ...
40c44,45
<                   callback: Optional[Callable[..., None]] = ...) -> AsyncResult: ...
---
>                   callback: Optional[Callable[..., None]] = ...,
>                   error_callback: Optional[Callable[[BaseException], None]] = ...) -> AsyncResult: ...
48a54,63
>     def starmap(self,
>                 func: Callable[..., Any],
>                 iterable: Iterable[Iterable[Any]] = ...,
>                 chunksize: Optional[int] = ...) -> List[Any]: ...
>     def starmap_async(self,
>                       func: Callable[..., Any],
>                       iterable: Iterable[Iterable[Any]] = ...,
>                       chunksize: Optional[int] = ...,
>                       callback: Optional[Callable[..., None]] = ...,
>                       error_callback: Optional[Callable[[BaseException], None]] = ...) -> AsyncResult: ...
53a69
>
```

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
Looks good, thanks for the thorough summary.

I wonder if we should put the multiprocessing stubs in 2and3. There don't seem to be major API changes between 2 and 3, just a few new features.
