### ISSUE TITLE
Incorrect stub for Descriptor on `types-protobuf` 3.19.22

### ISSUE THREAD

**Issue by mdczaplicki** [python/typeshed#8289]
After upgrading `types-protobuf` from 3.19.21 to 3.19.22 `mypy` started complaining about unexpected parameters:

```
ommon/eventbus/proto/events_pb2.py:33: error: Unexpected keyword argument "filename" for "Descriptor"
/usr/local/lib/python3.7/site-packages/google-stubs/protobuf/descriptor.pyi:33: note: "Descriptor" defined here
common/eventbus/proto/events_pb2.py:33: error: Unexpected keyword argument "fields" for "Descriptor"
/usr/local/lib/python3.7/site-packages/google-stubs/protobuf/descriptor.pyi:33: note: "Descriptor" defined here
common/eventbus/proto/events_pb2.py:33: error: Unexpected keyword argument "extensions" for "Descriptor"
/usr/local/lib/python3.7/site-packages/google-stubs/protobuf/descriptor.pyi:33: note: "Descriptor" defined here
common/eventbus/proto/events_pb2.py:33: error: Unexpected keyword argument "nested_types" for "Descriptor"
/usr/local/lib/python3.7/site-packages/google-stubs/protobuf/descriptor.pyi:33: note: "Descriptor" defined here
common/eventbus/proto/events_pb2.py:33: error: Unexpected keyword argument "enum_types" for "Descriptor"
/usr/local/lib/python3.7/site-packages/google-stubs/protobuf/descriptor.pyi:33: note: "Descriptor" defined here
common/eventbus/proto/events_pb2.py:33: error: Unexpected keyword argument "is_extendable" for "Descriptor"
/usr/local/lib/python3.7/site-packages/google-stubs/protobuf/descriptor.pyi:33: note: "Descriptor" defined here
common/eventbus/proto/events_pb2.py:33: error: Unexpected keyword argument "syntax" for "Descriptor"
/usr/local/lib/python3.7/site-packages/google-stubs/protobuf/descriptor.pyi:33: note: "Descriptor" defined here
common/eventbus/proto/events_pb2.py:33: error: Unexpected keyword argument "extension_ranges" for "Descriptor"
/usr/local/lib/python3.7/site-packages/google-stubs/protobuf/descriptor.pyi:33: note: "Descriptor" defined here
common/eventbus/proto/events_pb2.py:33: error: Unexpected keyword argument "oneofs" for "Descriptor"
```

Even though - when I get to `protobuf`'s `Descriptor` implementation - I can see:

```
    def __new__(
        cls,
        name=None,
        full_name=None,
        filename=None,
        containing_type=None,
        fields=None,
        nested_types=None,
        enum_types=None,
        extensions=None,
        options=None,
        serialized_options=None,
        is_extendable=True,
        extension_ranges=None,
        oneofs=None,
        file=None,  # pylint: disable=redefined-builtin
        serialized_start=None,
        serialized_end=None,
        syntax=None,
        create_key=None):
        ....

  # NOTE(tmarek): The file argument redefining a builtin is nothing we can
  # fix right now since we don't know how many clients already rely on the
  # name of the argument.
  def __init__(self, name, full_name, filename, containing_type, fields,
               nested_types, enum_types, extensions, options=None,
               serialized_options=None,
               is_extendable=True, extension_ranges=None, oneofs=None,
               file=None, serialized_start=None, serialized_end=None,  # pylint: disable=redefined-builtin
               syntax=None, create_key=None):
                ...
```

---

Oh, now I've realized that I have `protobuf` 3.20.1.
