### ISSUE TITLE
Remove version guard for __ne__()

### ISSUE THREAD

**Issue by utkarsh2102** [python/typeshed#2669]
Looks like we do not need the version guard anymore, do we?

https://github.com/python/typeshed/blob/3e4737c683497f3098a950d1609ffe34e55abebb/stdlib/2and3/decimal.pyi#L80-L81

A quick grep in `python/cpython` tells me this.

**Comment by utkarsh2102** [comment]
@srittau, what's your take on that?

**Comment by srittau** [comment]
Please be patient, I watch all issues in typeshed and will comment when I find time, no need to ping me. :)

 At least `_pydecimal` does not implement `__ne__()` directly, and actually the following will fail with Python 3.5.3, while it works with Python 2.7.13:

```python
from decimal import Decimal
Decimal(1).__ne__(Decimal(1), None)
```

So it seems the version check is still required.

**Comment by utkarsh2102** [comment]
> Please be patient, I watch all issues in typeshed and will comment when I find time, no need to ping me. :)

Sorry. 

> At least _pydecimal does not implement __ne__() directly

Ah, so all the implementations are to be checked? 
And if there's a restriction, it has to be added separately, right?

**Comment by srittau** [comment]
Since this uses a non-standard `__ne__()` (with a second argument), this had to be checked. Of course, the normal `Decimal(1) != Decimal(2)` will still work in Python 3, since it will just reverse the result of `__eq__()`.
