### ISSUE TITLE
Changes to `unittest.mock.ANY` make it harder to use

### ISSUE THREAD

**Issue by DanielNoord** [python/typeshed#14701]
Not sure if this is a regression, but I also don't see any discussion about it in https://github.com/python/typeshed/pull/14613
cc @donBarbos @srittau 

Because of the change to `ANY` (making it `_ANY` instead of `Any`) the following code no longer type checks with the latest version of `mypy`. While it used to do before.

```python
from unittest.mock import ANY

def func(x: str) -> None:
    ...
    
func(ANY)
func("s")
reveal_type(ANY)
```

I can't make up my mind whether this is intentional, but I guess most people that use `ANY` want to use it as a variant of `Any` and not as a redefinition of the `_ANY` class.
Can you confirm or deny whether this change is intentional?

**Comment by srittau** [comment]
This change was intentional. `ANY` is a sentinel intended to be used for certain `unittest.mock` functions, not a general value that's intended to be passed to user functions. If there are problems with the former, we need to address them, but type checkers complaining about the latter case seems like type checking working as intended.

**Comment by DanielNoord** [comment]
@srittau What about the following (made-up) use case:

```python
from random import random
from typing import TypedDict
from unittest.mock import ANY


class A(TypedDict):
    data: str
    non_important: float


def func(some_data: int) -> A:
    return {"data": str(some_data), "non_important": random()}


assert func(1) == A({"data": "1", "non_important": ANY})
```

We have other cases that don't involve `TypedDict` but a `pydantic.BaseModel`. Essentially we want to assert certain fields in a return value but don't care about others.
I personally think this is a valid use case of `ANY`, and the [documentation](https://docs.python.org/3/library/unittest.mock.html#any) seems to confirm this.

> [ANY](https://docs.python.org/3/library/unittest.mock.html#unittest.mock.ANY) is not limited to comparisons with call objects and so can also be used in test assertions:

On `1.17` this typechecks, on `1.18` and `master` it doesn't anymore.

**Comment by srittau** [comment]
I can see using `ANY` for custom test frameworks, although I'm still critical of using it outside its intended purpose. That said, deriving `_ANY` from `typing.Any` would probably allow those use cases.

**Comment by DanielNoord** [comment]
> I can see using `ANY` for custom test frameworks, although I'm still critical of using it outside its intended purpose. That said, deriving `_ANY` from `typing.Any` would probably allow those use cases.

Taken from the standard library documentation I linked:

```python
class TestStringMethods(unittest.TestCase):

    def test_split(self):
        s = 'hello world'
        self.assertEqual(s.split(), ['hello', ANY])
```

To me also reads as "Assert part of your data is as expected while ignoring the rest". I don't think that this use is outside of its intended purpose to be honest.
