### PR TITLE
Use Literal to improve SpooledTemporaryFile

### LINKED ISSUE #3360: read of SpooledTemporaryFile returns bytes, mypy assumes str
I think this is correct here and not in the `mypy` repo (if I'm wrong, I am happy to open a ticket there):

following code

```
from tempfile import SpooledTemporaryFile
stderrfile = SpooledTemporaryFile()
sterr_output = stderrfile.read().decode()
```

works fine with python3.7 . Using mypy (also with python 3.7) I get the following error:

```
$ python3 -m mypy test.py 
test.py:3: error: "str" has no attribute "decode"; maybe "encode"?
```

Mypy incorrectly assumes that the result of the read is a `str` but using the interactive interpreter you'll see that the `read` method actually returns a `byte` object. The type annotations  (https://github.com/python/typeshed/blob/master/stdlib/3/tempfile.pyi) say `AnyStr` as return type which is too narrow in this case.

### PR DESCRIPTION
**Pull request by aloisklink**
Specifies that a `SpooledTemporaryFile[bytes]` is constructed if we open the file in `bytes` mode,
and a `SpooledTemporaryFile[str]` is constructed if we open the file in `str` mode.

I've also ran `black` on the `stdlib/3/tempfile.pyi` file I changed, since [CONTRIBUTING.md](https://github.com/python/typeshed/blob/master/CONTRIBUTING.md) says that style-fixes are accepted.

I'm using the newly added to mypy python/typing#680 to do this, as @srittau recommended.

Fixes #3360.

Test case:

```python
import tempfile
with tempfile.SpooledTemporaryFile() as defaultmpfile:
    reveal_type(defaultmpfile)

with tempfile.SpooledTemporaryFile(mode="w+b") as bytetmpfile:
    reveal_type(bytetmpfile)

with tempfile.SpooledTemporaryFile(mode="w+") as strtmpfile:
    reveal_type(strtmpfile)
```

Prints the following with the latest version of mypy, so it looks like everything is working fine.

```console
me@test:~/typeshed/test_mypy_dir(improve-spooled-temporary-file)$ PYTHONPATH="mypy/:${PYTHONPATH}" python3 -m mypy test.py
test.py:3: note: Revealed type is 'tempfile.SpooledTemporaryFile[builtins.bytes]'
test.py:6: note: Revealed type is 'tempfile.SpooledTemporaryFile[builtins.bytes]'
test.py:9: note: Revealed type is 'tempfile.SpooledTemporaryFile[builtins.str]'
```

### CODE REVIEW

File: stdlib/3/tempfile.pyi [hunk 1]
```diff
@@ -93,17 +92,48 @@ def NamedTemporaryFile(
...
-                 buffering: int = ..., encoding: Optional[str] = ...,
-                 newline: Optional[str] = ..., suffix: Optional[str] = ...,
-                 prefix: Optional[str] = ..., dir: Optional[str] = ...
-                 ) -> None: ...
+    # bytes needs to go first, as default mode is to open as bytes
+    @overload
+    def __init__(
+        self: SpooledTemporaryFile[bytes],
+        max_size: int = ...,
+        mode: Literal["rb", "wb", "ab", "xb", "r+b", "w+b", "a+b", "x+b"] = ...,
```
Comment (srittau) [inline stdlib/3/tempfile.pyi]: Also just `"b"`.

File: stdlib/3/tempfile.pyi [hunk 2]
```diff
@@ -93,17 +92,48 @@ def NamedTemporaryFile(
...
+        newline: Optional[str] = ...,
+        suffix: Optional[str] = ...,
+        prefix: Optional[str] = ...,
+        dir: Optional[str] = ...,
+    ) -> None: ...
+    @overload
+    def __init__(
+        self: SpooledTemporaryFile[str],
+        max_size: int = ...,
+        mode: Literal["r", "w", "a", "x", "r+", "w+", "a+", "x+", "rt", "wt", "at", "xt", "r+t", "w+t", "a+t", "x+t"] = ...,
```
Comment (srittau) [inline stdlib/3/tempfile.pyi]: Also just `""`.

File: stdlib/3/tempfile.pyi (hunk 1 above)
Comment (aloisklink) [reply stdlib/3/tempfile.pyi]: The mode `"b"` and `""` both cause errors in Python 2.7 and 3.7. I haven't tested on other Python versions, but I don't see why they would be different.

Trying to instantiate a `TemporaryFile` (done when a `SpooledTemporaryFile` rolls over) with a mode string not containing exactly one of `rwax` and more than one `+` will raise `ValueError: Must have exactly one of create/read/write/append mode and at most one plus` on Python 3.7.4.

Python 2.7.16 has a similar error: `ValueError: mode string must begin with one of 'r', 'w', 'a' or 'U', not 'b'`.

Confusingly, the `SpooledTemporaryFile` constructor accepts any mode, but an exception is raised only when it creates a `TemporaryFile` internally. [This can be forced by using the `rollover()` function](https://docs.python.org/3/library/tempfile.html#tempfile.SpooledTemporaryFile).

Test case:

```python3
import tempfile
# this line works fine
with tempfile.SpooledTemporaryFile(mode="b") as tmpfile:
    # this line fails, since the invalid mode is checked here
    tmpfile.rollover()
```

File: stdlib/3/tempfile.pyi (hunk 2 above)
Comment (aloisklink) [reply stdlib/3/tempfile.pyi]: Same error as above on Python 3.7.4, Python 2.7.16 has it's own `ValueError: empty mode string` error. It is only seen after the SpooledTemporaryFile creates a `TemporaryFile` internally, which can be forced using `~SpooledTemporaryFile.rollover()`.

```python
import tempfile

with tempfile.SpooledTemporaryFile(mode="") as tmpfile:
    tmpfile.rollover() # empty mode fails on this line, not at constructor
```

**Comment by aloisklink** [comment]
Thanks for the review @srittau. I think the two modes you asked me to add are not valid modes. Confusingly, `SpooledTemporaryFile` only raises an `Error` about an incorrect modes when it internally calls `TemporaryFile`, which does not happen during the constructor.

There is a mode `U` that I haven't added, but it does nothing in Python 3, and the official docs for Python 2 say ["should not be used in new code."](https://docs.python.org/2/library/io.html#io.open), since it is replaced by the `newline` parameter.
