### PR TITLE
Improve types for subprocess module

### LINKED ISSUE #1004: subprocess.CalledProcessError cmd should accept List[str]
The stubs currently say cmd must be a str, even though the subprocess library itself can pass in a list.

I'll try to post a PR with a fix today or later this week.

### PR DESCRIPTION
**Pull request by jboning**
This adds union types in the constructor to account for parameters that
might be either byte strings or unicode strings. At the same time, this
*removes* specific types from the user-accessible fields, to avoid the
need for users to at every use site specify which types their particular
instance was instantiated with.

Fixes #1004

### CODE REVIEW

File: stdlib/2/subprocess.pyi [hunk 1]
```diff
@@ -57,10 +57,15 @@ STDOUT = ...  # type: int
 
 class CalledProcessError(Exception):
     returncode = 0
-    cmd = ...  # type: str
-    output = ...  # type: str  # May be None
+    # morally: Union[str, bytes, List[str], List[bytes]]
```
Comment (JelleZijlstra) [inline stdlib/2/subprocess.pyi]: str and bytes are the same thing in Python 2. You should use str and unicode, or bytes and Text if you want the same code in 2 and 3. (Maybe we can merge these stubs in the future?)

Comment (jboning) [inline stdlib/2/subprocess.pyi]: Oops! I guess I got mixed up because of the python 3 stub syntax.

File: stdlib/2/subprocess.pyi [hunk 2]
```diff
@@ -57,10 +57,13 @@ STDOUT = ...  # type: int
...
     returncode = 0
-    cmd = ...  # type: str
-    output = ...  # type: str  # May be None
+    cmd = ...  # type: Any
+    output = ...  # type: Any
 
-    def __init__(self, returncode: int, cmd: str, output: Optional[str] = ...) -> None: ...
+    def __init__(self,
+                 returncode: int,
+                 cmd: Union[bytes, Text, List[bytes], List[Text]],
```
Comment (JelleZijlstra) [inline stdlib/2/subprocess.pyi]: Instead of List, can't it be any Sequence? That's what check_output is annotated as.

File: stdlib/2/subprocess.pyi [hunk 3]
```diff
@@ -57,10 +57,13 @@ STDOUT = ...  # type: int
 
 class CalledProcessError(Exception):
     returncode = 0
-    cmd = ...  # type: str
-    output = ...  # type: str  # May be None
+    cmd = ...  # type: Any
```
Comment (JelleZijlstra) [inline stdlib/2/subprocess.pyi]: I think the "moral" comments were actually helpful here.

**Comment by JelleZijlstra** [comment]
Thanks! Sorry for not noticing the thing I commented on earlier.

File: stdlib/2/subprocess.pyi (hunk 3 above)
Comment (jboning) [inline stdlib/2/subprocess.pyi]: OK, I'll add them back! I thought they might be redundant with the actual types in the constructor.

File: stdlib/2/subprocess.pyi (hunk 2 above)
Comment (jboning) [inline stdlib/2/subprocess.pyi]: Ah indeed! Should I modify check_output (and family) to support bytes, too?

Comment (JelleZijlstra) [inline stdlib/2/subprocess.pyi]: Sure, please do. Also, I think the argument should be `Sequence[Union[bytes, Text]]`, since mixing bytes and str seems to work fine. Using a Union as the type argument is OK because Sequence is covariant.

File: stdlib/3/subprocess.pyi [hunk 4]
```diff
@@ -2,37 +2,42 @@
 
 # Based on http://docs.python.org/3.6/library/subprocess.html
 import sys
-from typing import Sequence, Any, AnyStr, Mapping, Callable, Tuple, IO, Optional, Union, List, Type
+from typing import Sequence, Any, AnyStr, Mapping, Callable, Tuple, IO, Optional, Union, List, Type, Text
 from types import TracebackType
 
+_FILE = Union[int, IO[Any]]
```
Comment (jboning) [inline stdlib/3/subprocess.pyi]: I brought this _FILE thing over from the python 2 stubs, though I'm actually not sure it's correct.

**Comment by jboning** [comment]
I've standardized on `Union[bytes, Text]` everywhere that strings are used in the subprocess module, since it seems happily to accept either, and `Any` everywhere that a return type might be either `bytes` or `Text`.

There's still a disorganized mixture of Optional and non-Optional arguments. Maybe I should also standardize this to have the explicit Optional everywhere? (Or maybe I should stop offering to incorporate more changes into this PR so that it can eventually get merged :P)

**Comment by JelleZijlstra** [comment]
Feel free to add more changes; I'll review it tonight and merge if I don't see any other issues.

File: stdlib/2/subprocess.pyi [hunk 5]
```diff
@@ -2,65 +2,73 @@
...
                  shell: bool = ...,
-                 cwd: str = ...,
-                 env: Mapping[str, str] = ...,
+                 cwd: _TXT = ...,
+                 env: Mapping[_TXT, _TXT] = ...,
                  universal_newlines: bool = ...,
                  startupinfo: Any = ...,
-                 creationflags: int = ...) -> str: ...
+                 creationflags: int = ...
+                 ) -> Any: ...  # morally: _TXT
```
Comment (JelleZijlstra) [inline stdlib/2/subprocess.pyi]: Can it really return unicode in py2? It returns str for me even with universal_newlines on. (In Python 3 it's bytes without universal_newlines and str with it.)

File: stdlib/2/subprocess.pyi [hunk 6]
```diff
@@ -70,33 +78,31 @@ class Popen:
...
+                 env: Optional[Mapping[_TXT, _TXT]] = ...,
                  universal_newlines: bool = ...,
                  startupinfo: Optional[Any] = ...,
                  creationflags: int = ...) -> None: ...
 
     def poll(self) -> int: ...
     def wait(self) -> int: ...
-    def communicate(self, input: Optional[AnyStr] = ...) -> Tuple[Optional[bytes], Optional[bytes]]: ...
+    # morally: -> Tuple[_TXT, _TXT]
+    def communicate(self, input: Optional[_TXT] = ...) -> Tuple[Any, Any]: ...
```
Comment (JelleZijlstra) [inline stdlib/2/subprocess.pyi]: I think the original return annotation was also correct here.

File: stdlib/3/subprocess.pyi (hunk 4 above)
Comment (JelleZijlstra) [inline stdlib/3/subprocess.pyi]: You can actually pass file descriptors (i.e., ints) to the stdout and stderr arguments in both Python 2 and 3. Didn't know about this either, but it seems to work.

File: stdlib/3/subprocess.pyi [hunk 7]
```diff
@@ -214,15 +222,21 @@ if sys.version_info >= (3, 3):
...
+        # morally: Optional[_TXT]
+        stdout = ...  # type: Any
+        stderr = ...  # type: Any
 
-    def __init__(self, returncode: int, cmd: str, output: Optional[str] = ...,
-                 stderr: Optional[str] = ...) -> None: ...
+    def __init__(self,
+                 returncode: int,
+                 cmd: _CMD,
+                 output: Optional[_TXT] = ...,
```
Comment (JelleZijlstra) [inline stdlib/3/subprocess.pyi]: Odd that this argument isn't called "stdout", but confirmed in the source that it's true.

Comment (jboning) [inline stdlib/3/subprocess.pyi]: yeah; I think that's because it predates the addition of "stderr", and the "stdout" alias was added at the same time for consistency.

File: stdlib/2/subprocess.pyi (hunk 5 above)
Comment (jboning) [inline stdlib/2/subprocess.pyi]: Indeed; fascinating! I didn't compare the documentation for the different versions closely enough. It looks like in python 2, the difference is that `os.fdopen()` is called with "U" in the mode to; but file objects with universal newlines turned still just return strings. I think that means I should convert all of the py2 output/stderr types to be `bytes`.

File: stdlib/2/subprocess.pyi (hunk 6 above)
Comment (jboning) [inline stdlib/2/subprocess.pyi]: I think `Any` is preferable in the same way it is for the other sort of `output` annotations; with `Optional`, a user who passed in a `PIPE` must explicitly check for None (or cast). I'm updating the descriptive comment to say the right thing though (the original annotation).

**Comment by JelleZijlstra** [comment]
Merged! Thanks for all the fixes.

**Comment by jboning** [comment]
Thanks for the several rounds of review!

**Comment by gvanrossum** [comment]
Sadly now the mypy tests fail, like this:
```
PARALLEL 2
SUMMARY  139 tasks selected
passed 22, failed 1, pending 115; running 1                                     

FAILURE  #23 check file runtests.py

mypy/waiter.py:36: error: Argument 3 to "Popen" has incompatible type Dict[str, str]; expected Mapping[Union[bytes, str], Union[bytes, str]]
mypy/test/testpythoneval.py:123: error: Argument 2 to "Popen" has incompatible type Dict[str, str]; expected Mapping[Union[bytes, str], Union[bytes, str]]

passed 26, failed 2, pending 110; running 1                                     

FAILURE  #27 check package mypy

mypy/waiter.py:36: error: Argument 3 to "Popen" has incompatible type Dict[str, str]; expected Mapping[Union[bytes, str], Union[bytes, str]]
mypy/test/testpythoneval.py:123: error: Argument 2 to "Popen" has incompatible type Dict[str, str]; expected Mapping[Union[bytes, str], Union[bytes, str]]

passed 118, failed 3, pending 17; running 1                                     

FAILURE  #121 check stdlibsamples (3.2)

subprocess.py:1586: error: Need type annotation for variable
test/test_subprocess.py:1294: error: Need type annotation for variable

SUMMARY  3/139 tasks and 3/3981 tests failed
 FAILURE check file runtests.py
 FAILURE check package mypy
 FAILURE check stdlibsamples (3.2)
SUMMARY  3/139 tasks and 3/3981 tests failed
*** FAILURE ***
```

**Comment by JelleZijlstra** [comment]
Oh no :(. I guess it's because Mapping is covariant in the value type but not the key type (not sure why). If that's true, we should be able to fix by reverting the key type to `str`. I can confirm whether that works and submit a PR tonight.

**Comment by jboning** [comment]
The stdlibsamples test failures mystified me for a moment; but I think those are actually a result of #1080 now that there are more, and more specific, annotations for `select()`.

**Comment by JelleZijlstra** [comment]
I just posted a PR in #1090 to add a tox.ini that includes a way to test mypy's test suite against typeshed. I'll send a followup PR later to include it in Travis. (I'd prefer to catch these issues before we merge.)

**Comment by gvanrossum** [comment]
FWIW all you need to do to repro this is `mypy runtests.py`.

**Comment by jboning** [comment]
Indeed, switching the key type back to `str` works. `Union[Mapping[str, _TXT], Mapping[bytes, _TXT]]` also makes the mypy tests pass. It seems like that might be better since it's a little more flexible; what do you think?

**Comment by gvanrossum** [comment]
I'll send a PR.

**Comment by gvanrossum** [comment]
#1091. (It does not fix the issue introduced by #1080, see discussion there.)
