### ISSUE TITLE
Revealed type of click decorators is Any

### ISSUE THREAD

**Issue by SnoopJeDi** [python/typeshed#6156]
**NOTE:** Appears to be caused by #5483. Issue **does not occur** against stubs prior to 7a9a107 (e.g. with `types-click==0.1.12`).

The stubs for `click` annotate the return type of many of the library's decorator factories as `IdentityFunction` (e.g. see [`argument` stub](https://github.com/python/typeshed/blob/master/stubs/click/click/decorators.pyi#L58-L73), but the revealed type when running `mypy` is `Any`. See sample program below.

I'm not sure if this is indicative of an underlying bug in `mypy` or if there's something missing in the usage of `IdentityFunction` from `typeshed` that keeps it from resolving that helper. Insight from someone who is more familiar with the details would be appreciated.

### Sample program
```python
import click

reveal_type(click.argument("foo"))

@click.command()
@click.argument("foo")
def cli(foo: str) -> None:
    ...

reveal_type(cli)
```

### Output
```
2:17 [snoopjedi@denton ~]
$ python3 -m mypy --strict repro.py 
repro.py:3: note: Revealed type is "Any"
repro.py:6: error: Untyped decorator makes function "cli" untyped
repro.py:10: note: Revealed type is "click.core.Command"
Found 1 error in 1 file (checked 1 source file)
```

### Version information
* Python: 3.8.10
* `mypy`: 0.910
* `types-click`: 7.1.6

**NOTE:** I am submitting this issue on behalf of a user who asked a question about it in #python on the Libera IRC network.

**Comment by SamJoan** [comment]
For what it's worth, I experienced this regression when migrating between development environments due to a pinned dependency which itself pinned `click`. 

I'm going to completely redo my dependency management in this case because it just makes sense but definitely a regression imo, not sure if it will impact anything else.

**Comment by hauntsaninja** [comment]
The only other report we've had of this kind of problem is with `types-retry`.
I agree this is problematic and really tough for users to debug, it's something we're now much more aware of / I don't think we really anticipated when we shifted to modular typeshed. There's more discussion in #5751.
