### ISSUE TITLE
multiprocessing.pool module missing from Python 2 stubs

### ISSUE THREAD

**Issue by iwiwi** [python/typeshed#1925]
`multiprocessing.pool.ThreadPool` is useful (see http://lucasb.eyer.be/snips/python-thread-pool.html).

```python
import time
import multiprocessing.pool


def func(x):
    # type: (int) -> int
    time.sleep(x)
    return x


def main():
    # type: () -> None
    pool = multiprocessing.pool.ThreadPool(2)
    ite = pool.imap(func, range(10), chunksize=1)

    try:
        while True:
            x = ite.next(timeout=3)
            print(x)
    except multiprocessing.TimeoutError:
        print('timeout')
    

if __name__ == '__main__':
    main()
```

The code works on Python 2.7 as follows. (The code looks similar to #1923, but here we use `multiprocessing.pool.ThreadPool`, instead of `multiprocessing.Pool`)

```
$ python --version
Python 2.7.14
$ python bar.py
0
1
2
3
4
timeout
```

However, `mypy` fails as follows (even if we add `--ignore-missing-import`).

```
$ mypy --version
mypy 0.570-dev-c594761aa1dbe76a3a0bc199b03fbf684ce588d8
$ mypy --python-version 2.7 bar.py
bar.py:2: error: No library stub file for standard library module 'multiprocessing.pool'
bar.py:2: note: (Stub files are from https://github.com/python/typeshed)
bar.py:13: error: Module has no attribute "pool"
$ mypy --ignore-missing-import --python-version 2.7 bar.py
bar.py:13: error: Module has no attribute "pool"
```

**Comment by gvanrossum** [comment]
Do you want to contribute a stub for `pool`?

**Comment by iwiwi** [comment]
I'm happy to work on it. First, I submitted PR #1926 for issue #1924. I will work on this issue next, as the Python 2 stub should have `next(timeout)` method, too.
