### ISSUE TITLE
"csv.writer.write" does not work for objects expecting something other than "str" in their "write" method

### ISSUE THREAD

**Issue by deveshks** [python/typeshed#3997]
This was originally found when upgrading [pip](https://github.com/pypa/pip/) to `mypy 0.770` in https://github.com/pypa/pip/pull/8235

There was a change made to `_csv.pyi` in https://github.com/python/typeshed/pull/3581 which hardcodes the input type of `_Writer.write` to `str`

https://github.com/python/typeshed/blob/6dca3f7fc52e84e3c6b512bb4a6d462778d6a692/stdlib/2and3/_csv.pyi#L44-L45

If I understand correctly, as per the [csv.writer docs](https://docs.python.org/3/library/csv.html#csv.writer) , `csvfile can be any object with a write() method`, which means that things like [io.BytesIO](https://docs.python.org/3/library/io.html#io.BytesIO) whose [write](https://docs.python.org/3/library/io.html#io.BufferedIOBase.write) accepts `bytes-like object` will fail typechecking

A minimal reproducer for this is as follows, and the type checking was done against `mypy 0.770`
and `python 3.8.2`
```
import csv
import io

buffer = io.BytesIO()
wrt = csv.writer(buffer)
```

And the output is

```
$ mypy --version
mypy 0.770

$ python --version
Python 3.8.2

$ mypy scratch.py 
scratch.py:5: error: Argument 1 to "writer" has incompatible type "BytesIO"; expected "_Writer"
scratch.py:5: note: Following member(s) of "BytesIO" have conflicts:
scratch.py:5: note:     Expected:
scratch.py:5: note:         def write(self, s: str) -> Any
scratch.py:5: note:     Got:
scratch.py:5: note:         def write(self, Union[bytes, bytearray]) -> int
Found 1 error in 1 file (checked 1 source file)
```

Also note that this worked in `mypy 0.760`

```
$ mypy --version
mypy 0.760

$ mypy scratch.py 
Success: no issues found in 1 source file
```

**Comment by srittau** [comment]
@deveshks You will notice that your example will fail as soon as you try to actually use the writer you just created:

```python
import csv
import io

buffer = io.BytesIO()
wrt = csv.writer(buffer)
wrt.writerow([])  # TypeError
```

While using `io.StringIO()` works. I have used the `csv` module only casually though, so I might be misunderstanding how it's supposed to work.

**Comment by JelleZijlstra** [comment]
Indeed the C code for csv always calls `write()` with a str argument: https://github.com/python/cpython/blob/6b6092f533f0e4787b8564c4fad6ec6d1018af0d/Modules/_csv.c#L1244

**Comment by deveshks** [comment]
So given the facts that the mypy type checking not working is due to the code example which doesn't work as well, I will go ahead and close this issue
