### PR TITLE
Revert "Add `__new__` to `str` and `int` stubs in both Pythons. (#1352)"

### LINKED ISSUE #1464: Issues with enum indexing
I encountered some issues with indexing on enum classes that use multiple inheritance. I'm using the following test script:
```python
from enum import Enum
from typing import TYPE_CHECKING

if not TYPE_CHECKING:
    reveal_type = print

class I(int, Enum):
    a = 1
reveal_type(I['a'])  # E: Revealed type is '__main__.I'

class S(str, Enum):
    a = '1'
reveal_type(S['a'])  # E: Revealed type is '__main__.S'

class F(float, Enum):
    a = 1.0
reveal_type(F['a'])  # E: Revealed type is '__main__.F'
```
All of this works at runtime; it prints I.a, S.a, F.a.

With current mypy master (incorporating most recent typeshed changes) I get:
```
$ mypy bin/enumindex.py 
bin/enumindex.py:7: error: Definition of "__new__" in base class "int" is incompatible with definition in base class "Enum"
bin/enumindex.py:9: error: Revealed type is 'Any'
bin/enumindex.py:9: error: Value of type Type[I] is not indexable
bin/enumindex.py:11: error: Definition of "__new__" in base class "str" is incompatible with definition in base class "Enum"
bin/enumindex.py:13: error: Revealed type is 'Any'
bin/enumindex.py:13: error: Value of type Type[S] is not indexable
bin/enumindex.py:17: error: Revealed type is 'enumindex.F'
```
With the most recent mypy release it's better:
```
$ mypy bin/enumindex.py 
bin/enumindex.py:9: error: Revealed type is 'enumindex.I'
bin/enumindex.py:13: error: Revealed type is 'Any'
bin/enumindex.py:13: error: Value of type "S" is not indexable
bin/enumindex.py:17: error: Revealed type is 'enumindex.F'
```

So there's a regression, which is caused by #1352 (cc @sproshev). Perhaps we should revert that PR? It fixed a relatively obscure case, and multiple inheritance from Enum is explicitly mentioned in the docs (https://docs.python.org/3/library/enum.html#others).

But the previous behavior was buggy too: somehow indexing worked on multiple inheritance from float or int, but not str. I'm not sure how to explain that yet. It doesn't reproduce in a mypy test, so presumably it's due to something in the typeshed stubs.

### PR DESCRIPTION
**Pull request by JelleZijlstra**
This reverts commit fed4e03e5370058a1929db8c48ab5e9e93bbd350.

See #1464.

This doesn't completely fix #1464; I still get "bin/enumindex.py:9: error: Value of type Type[I] is not indexable" for an enum inheriting from int and Enum. But some of the errors are gone.

### CODE REVIEW

File: third_party/2/enum.pyi [hunk 1]
```diff
@@ -16,7 +16,6 @@ class Enum(metaclass=EnumMeta):
     name = ...  # type: str
     value = ...  # type: Any
 
-class IntEnum(int, Enum):  # type: ignore
-    def __new__(cls: Type[_T], value: Any) -> _T: ...
+class IntEnum(int, Enum): ...
```
Comment (matthiaskramm) [inline third_party/2/enum.pyi]: If you're removing the explicit `__new__`, would it make sense to make the base class order "Enum, int" so that `__new__` is inherited from `Enum`, not `int`?

Comment (JelleZijlstra) [inline third_party/2/enum.pyi]: I also removed `__new__` from int, so I don't think that makes a difference. Int comes first at runtime (https://github.com/python/cpython/blob/master/Lib/enum.py#L639), so putting Enum first here will probably break something.
