### PR TITLE
Add IOBase to types fcntl will accept as files

### LINKED ISSUE #1548: fcntl.flock no longer typechecks with io.FileIO argument
Seems like an edge case broken by the change in https://github.com/python/typeshed/pull/1505:

This code works in reality, but mypy does not like it:

```python
import io
import fcntl


with io.FileIO('hello.txt', mode='a+', closefd=True) as f:
    fcntl.flock(f, fcntl.LOCK_EX)
    print("hey it works")
    fcntl.flock(f, fcntl.LOCK_UN)
```

```
$ python ./blurp.py
hey it works
$ mypy ./blurp.py
blurp.py:6: error: Argument 1 to "flock" has incompatible type "IOBase"; expected "Union[int, IO[Any]]"
blurp.py:8: error: Argument 1 to "flock" has incompatible type "IOBase"; expected "Union[int, IO[Any]]"
```

### PR DESCRIPTION
**Pull request by OddBloke**
Anything that implements a fileno() method is acceptable (per https://github.com/python/cpython/blob/master/Objects/fileobject.c#L168-L173), and IOBase fits the bill.

Fixes #1548.

### CODE REVIEW

File: stdlib/3/fcntl.pyi [hunk 1]
```diff
@@ -1,6 +1,6 @@
 # Stubs for fcntl
+from io import IOBase as _IOBase
```
Comment (JelleZijlstra) [inline stdlib/3/fcntl.pyi]: You don't need the `as _IOBase` here.

**Comment by JelleZijlstra** [comment]
This feels a bit too ad hoc, but I suppose it's the best we can do until we have protocols. Can you fix the small style comment I added?

File: stdlib/3/fcntl.pyi (hunk 1 above)
Comment (OddBloke) [inline stdlib/3/fcntl.pyi]: Fixed.
