### PR TITLE
Add sockets attribute to asyncio.events.AbstractServer

### LINKED ISSUE #2334: "AbstractServer" has no attribute "sockets"
The last line here:

```
f = self._loop.create_server(self._handler, '0.0.0.0', 8080)
self._srv = self._loop.run_until_complete(f)
logger.info('serving on %s', self._srv.sockets[0].getsockname())
```

Gives the following error:

```
robotica/plugins/inputs/http.py:88: error: "AbstractServer" has no attribute "sockets"
```

However I believe this code matches the example:

http://asyncio.readthedocs.io/en/latest/tcp_echo.html

This broke when upgrading mypy from 0.610 to 0.620.

### PR DESCRIPTION
**Pull request by ymyzk**
Fixes #2334 / Corresponding [Python Docs](https://docs.python.org/3/library/asyncio-eventloop.html?highlight=create_server#asyncio.Server.sockets).

I noticed that this class has some changes in Python 3.7, so we need to update it again in the near future. This PR is intended for a quick fix of #2334.

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
Thanks!
